### ISSUE TITLE
Better API for HTTP Headers

### ISSUE THREAD

**Issue by codebien** [grafana/xk6-output-prometheus-remote#101]
k6 does not support the most used case of the current API for setting the custom HTTP Headers, which is the Cortex authentication. See https://github.com/grafana/k6/pull/2904 for details.

The suggestion is to deprecate the current API and replace it with a fixed environment variable name supported by k6. (e.g. `K6_PROMETHEUES_RW_HTTP_HEADERS` and use the value for the key-values binding. k6 uses the same approach for the tags' customization in the tagsInfluxDBv1 output.

```
K6_PROMETHEUES_RW_HTTP_HEADERS=X-Scope-OrgID:<org>,X-ANOTHER_HEADER:val
```

**Comment by lanore78** [comment]
Hi @codebien 

It would be really great if you let me know the estimated time for this issue to be released.
We've been researching new performance test tools that can replace LoadRunner, and currently K6 is the most likely tools to replace LoadRunner.

**Comment by codebien** [comment]
Hi @lanore78,
>It would be really great if you let me know the estimated time for this issue to be released.

We don't have an estimated time for this, it could be considered in the next weeks. If you want to speed up the process, you may consider contributing with a PR. The required code should be doable for an external contributor with a bit of Go knowledge.
