### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by yorugac** [grafana/xk6-output-prometheus-remote#106]
There's a security alert from dependabot:
https://github.com/grafana/xk6-output-prometheus-remote/security/dependabot/11

It requires updating `golang.org/x/text` package to > v0.3.8, but it appears to be an indirect dependency from k6 lib:
```
go.k6.io/k6@v0.41.1-0.20221116104224-5fa71b761185 golang.org/x/text@v0.3.7
```
Please update dependencies to resolve the alert.

**Comment by codebien** [comment]
It is waiting for https://github.com/grafana/k6/pull/2931
