### ISSUE TITLE
K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM doesn't generate histogram

### ISSUE THREAD

**Issue by boniek83** [grafana/xk6-output-prometheus-remote#108]
When K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM is set to true no histogram is generated at all:
https://imgur.com/a/HRes6iz

I'm using k6-operator with following docker image:
ghcr.io/grafana/operator:latest-runner (at time of my testing it was:
ghcr.io/grafana/operator@sha256:3f33890b2c94f55d8d886ee184dde69025dc2357970b63f0f837a4659b812aa4)
and this is crd config:
```---
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-test
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-test
      file: test.js
  arguments: --out experimental-prometheus-rw --tag testid=k6-test
  runner:
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push
      - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
        value: 1s
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: 'true'

**Comment by codebien** [comment]
Hi @boniek83, 
are you using Mimir? Mimir doesn't yet support the native histogram. Can you clarify why do you expect it should work?

**Comment by boniek83** [comment]
I expected that Mimir supports native histograms already. I was mistaken. Thanks!
