### ISSUE TITLE
Win10 does  not support  'output-prometheus-remote'

### ISSUE THREAD

**Issue by 15234660879** [grafana/xk6-output-prometheus-remote#12]
ERRO[0000] invalid output type 'output-prometheus-remote', available types are: cloud, csv, influxdb, json, statsd

**Comment by yorugac** [comment]
Hi @15234660879,
Thanks for opening the issue. Could you please elaborate on the steps you used to build and start k6 with the extension?

**Comment by 15234660879** [comment]
I used this command--"k6 run requestScript.js -o output-prometheus-remote".And the "requestScript" just is sample script，but result is "ERRO[0000] invalid output type 'output-prometheus-remote', available types are: cloud, csv, influxdb, json, statsd"

import http from 'k6/http';
var url = 'https://httpbin.test.k6.io/post';
export default function () {
  const data = { name: 'Bert' };
  let res = http.request('POST', url, JSON.stringify(data), {
    headers: { 'Content-Type': 'application/json' },
  });
  console.log(res.json().json.name);
  res = http.request('POST', url, data);
  console.log(res.json().form.name); 
}

**Comment by opravil-jan** [comment]
Hi,

any progress with this issue?

**Comment by javaducky** [comment]
Hi @15234660879 and @opravil-jan!

I'm just now seeing this issue, but I don't think there is anything to do here. Based upon the example usage provided by @15234660879 , this is correct behavior. 

So...the `xk6-output-prometheus-remote` is an *extension* to k6, and as such, needs to be compiled into the k6 binary using xk6. If you do not build a new k6 binary with the extension using xk6, you will see the message as shown.

Following the steps in the [Usage section of the README](https://github.com/grafana/xk6-output-prometheus-remote#usage), you should be able to create your extended k6 binary to publish metrics to Prometheus from a Windows installation, but will require that you have a Go(lang) development environment configured.
