### ISSUE TITLE
Does not build for ARM

### ISSUE THREAD

**Issue by mem** [grafana/xk6-output-prometheus-remote#131]
```
/go/pkg/mod/github.com/grafana/xk6-output-prometheus-remote@v0.1.0/pkg/remote/client.go:120:35: cannot use 0xffffffff (untyped int constant 4294967295) as int value in argument to fmt.Errorf
(overflows)
```

fix is straightforward.

**Comment by codebien** [comment]
I'm closing because as explained in https://github.com/grafana/xk6-output-prometheus-remote/pull/132#issuecomment-1630422075, it is expected. Feel free to reopen with more details.
