### ISSUE TITLE
Can we use this extension with pushgateway

### ISSUE THREAD

**Issue by nareshgnT** [grafana/xk6-output-prometheus-remote#14]
I tried using this extension with pushgateway and got this error `server returned HTTP status 405 Method Not Allowed: Method Not Allowed`

if this extension does not work with pushgateway then is there any other way to send metrics using pushgateway?

**Comment by yorugac** [comment]
Hi @nareshgnT, I'm afraid no, Pushgateway is quite a different beast and uses another format. Remote write is using its own [experimental serialization](https://docs.google.com/document/d/1LPhVRSFkGNSuU1fBd81ulhsCPR4hkSZyyBj1SZ8fWOM/edit#heading=h.3p42p5s8n0ui) while Pushgateway, AFAIK, is using [Prometheus Client Data Exposition Format](https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit).

So this extension is for writing metrics from k6 test run to `remote_write` endpoint only.

I'd say those two are also meant for a somewhat different use cases :thinking: I assume you have a dependency on Pushgateway? Is it possible to expose Prometheus directly, with `--enable-feature=remote-write-receiver` flag?

**Comment by unlikelyzero** [comment]
@nareshgnT @yorugac as of 2.33, remote_write is no longer an experimental feature and should be considered beta

**Comment by yorugac** [comment]
This question appears to have been answered so closing it.
