### ISSUE TITLE
Install xk6-output-prometheus-remote with other extensions

### ISSUE THREAD

**Issue by fdenUM** [grafana/xk6-output-prometheus-remote#141]
I am trying to build a k6 binary using xk6 to add the extensions that I need. First of all, I downloaded the latest version of xk6:

`go install go.k6.io/xk6/cmd/xk6@latest`

After that, I have the xk6 executable, so I will add only the "xk6-output-prometheus-remote" extension:

```
./xk6 build --with github.com/grafana/xk6-output-prometheus-remote@latest
xk6 has now produced a new k6 binary which may be different than the command on your system path!
```

As you can see, everything is fine if I add just that extension. But now, I will add the xk6-kafka extension, so I type the next:

`./xk6 build --with github.com/grafana/xk6-output-prometheus-remote@latest --with github.com/mostafa/xk6-kafka@latest`

And I get the next error complaining about the xk6-output-prometheus-remote:

```
# github.com/grafana/xk6-output-prometheus-remote/pkg/remotewrite
../../pkg/mod/github.com/grafana/xk6-output-prometheus-remote@v0.2.3/pkg/remotewrite/remotewrite.go:173:13: t.Total undefined (type *"go.k6.io/k6/metrics".TrendSink has no field or method Total)
../../pkg/mod/github.com/grafana/xk6-output-prometheus-remote@v0.2.3/pkg/remotewrite/trend.go:28:23: undefined: metrics.NewTrendSink
2023/08/30 10:45:35 [INFO] Cleaning up temporary folder: .../go/bin/buildenv_2023-08-30-1045.725323668
2023/08/30 10:45:35 [FATAL] exit status 1
```

If a try to execute a normal xk6 build with other extensions, I have no issues:

`./xk6 build --with github.com/mostafa/xk6-kafka@latest --with github.com/mostafa/xk6-sql@latest --with github.com/mostafa/xk6-output-influxdb@latest`

And again, everything is fine.

I tried to look if it extension has something special to install it but i couldn't find anything.

I also tried to build the k6 binary using containers as the oficial documentation but the output is the same using a container.

it looks like I cannot install any other extension if I install the prometheus one.

Please, can you help me?

**Comment by codebien** [comment]
Hey @fdenUM,
we have pushed the issue on the xk6-kafka extension. You should now be able to build it referencing the `main` branch:

```
xk6 build --with github.com/grafana/xk6-output-prometheus-remote@latest --with github.com/mostafa/xk6-kafka@main
```

Let me know if you still get the issue.
