### ISSUE TITLE
Bug On HTTP Failed Request

### ISSUE THREAD

**Issue by rodneyosodo** [grafana/xk6-output-prometheus-remote#152]
# Description

There is a bug on getting failed requests for the grafana dashboard

## Actual Bug

From this line https://github.com/grafana/xk6-output-prometheus-remote/blob/0afae1aea787965398ca62d07593d6498fecc43b/grafana/dashboards/k6-prometheus-native-histogram.json#L414C15-L414C15 is the query should be `expected_response="true"` which doesn't return failed requests

## Suggestion

Change to `expected_response="true"`

**Comment by ppcano** [comment]
Fixed by #153.

@rodneyosodo, thanks for taking the time to report this issue.
