### ISSUE TITLE
Improve Grafana dashboard in the example

### ISSUE THREAD

**Issue by javaducky** [grafana/xk6-output-prometheus-remote#19]
Improve upon the currently provided dashboard (`example/dashboards/default.json`). 

Another goal for this change would be to align the look-and-feel for the Prometheus-backed dashboard (this extension), the [xk6-output-influxdb](https://github.com/grafana/xk6-output-influxdb), and [xk6-output-timescaledb](https://github.com/grafana/xk6-output-timescaledb) possibly with the output provided by the [k6 Cloud App](https://grafana.com/grafana/plugins/grafana-k6-app/). This would provide a consistent user experience for the varied data sources.

Ideally, this dashboard would be promoted to the Grafana site as the "official" dashboard for displaying k6 metrics backed by Prometheus/Cortex/Mimir datasources.

**Comment by jwcastillo** [comment]
[](https://github.com/grafana/xk6-output-prometheus-remote/pull/94 ) 
this pr could close this ticket

**Comment by javaducky** [comment]
Fixed by #94.

**Comment by javaducky** [comment]
Dashboard is now available in Grafana community at https://grafana.com/grafana/dashboards/18030-test-result/ .
