### ISSUE TITLE
Http requests count double with 'constant-arrival-rate' executor

### ISSUE THREAD

**Issue by nanointeractive** [grafana/xk6-output-prometheus-remote#26]
I'm using the latest `v0.38.0` version of the k6 with the `xk6-output-prometheus-remote` extension.  
I've tried several scenarios with the `constant-arrival-rate` executor and always got the same results.  The `iterations` metric was counted two times more than expected. 
I've created the simple Counter to prove my theory and got the same 'doubled' results. 

Here is an example script:
```
import http from 'k6/http';
import {Counter} from 'k6/metrics';

export const options = {
    linger: true,
    scenarios: {
        contacts: {
            executor: 'constant-arrival-rate',
            duration: '30s',
            rate: 10,
            timeUnit: '1s',
            preAllocatedVUs: 1,
            maxVUs: 150,
        },
    },
};


const durationCounter = new Counter('dur_counter');

export default function () {

    var res = http.get('http://test.k6.io');

    if (res.status == 200) {
        durationCounter.add(1);
    }
}
```

Here are the results
<img width="851" alt="Screenshot 2022-06-05 at 21 46 44" src="https://user-images.githubusercontent.com/32302052/172067967-3f198ab5-9879-418e-9f46-a2fbd2f46852.png">

The number of HTTP requests sent to the server is correct, I've checked on my local machine (10 qps).

**Comment by na--** [comment]
I am confused, the underlined numbers in your screenshot are the same and they seem correct at a glance (10 iter/s * 30 seconds means roughly 600 requests, which is what you get).

**Comment by na--** [comment]
Ah, sorry, just saw what you mean, right after I posted my comment above :sweat_smile:  :man_facepalming: You are wondering why `http_reqs` is 2x the number of `iterations`, right?

The answer for that is simple, `http://test.k6.io` actually redirects to `https://test.k6.io`;
```
$ curl -I 'http://test.k6.io'
HTTP/1.1 308 Permanent Redirect
...
Location: https://test.k6.io/
```

So, k6 will actually make (and measure) 2 HTTP requests for every iteration.

**Comment by nanointeractive** [comment]
Sorry for the confusion :D but the issue still remains, it's about iterations, not the HTTP requests.

Please look at the `iterations` metric. I've configured a constant rate of 10 iterations/s with a duration of 30 seconds. In total, I should get around `300 iterations` and the result is `586 iterations`, 2x more.

Also, look at the custom counter `dur_counter`. It is fired only on `status==200` and it shows also `586 iterations`. I don't have time to check the source code but I'm sure that some event is firing two times instead of one causing the counters to count +2 for one iteration.

**Comment by nanointeractive** [comment]
yup, all fine, now it works, thanks !
