### ISSUE TITLE
Push Docker image

### ISSUE THREAD

**Issue by Moon1706** [grafana/xk6-output-prometheus-remote#32]
Hi folks! Why don't you want to push your docker images to the official registry? For example, I wanna export the result of K6 testing performance to Prometheus in Keptn and I must write the image name, I can't build it. Now I've upped a fork, but maybe you're gonna use GHA to push image?

**Comment by javaducky** [comment]
Hi @Moon1706. Because k6 can be extended with multiple extensions, we'd end up having to create so many permutations of images having varying extensions included, so it's easier to just have folks build their own custom images containing all the features they want. We've been including the `Dockerfile` locally to ease the process of creating your own custom image which could be pushed to their own container registry.

I'll discuss this internally if we want to start pushing images with just this extension. Obviously, anyone wishing to include an additional extension would have the same issue in that they'd have to build the image on their own.

**Comment by Moon1706** [comment]
If you do not agree on this issue, you can leave this issue open and people can use [my image](https://hub.docker.com/r/moon1706/xk6-output-prometheus-remote). It's a matter of trust, but my image is built from [the fork](https://github.com/Moon1706/xk6-output-prometheus-remote) of your repository with [one additional commit](https://github.com/grafana/xk6-output-prometheus-remote/compare/main...Moon1706:xk6-output-prometheus-remote:main).

**Comment by ppcano** [comment]
An official Docker image would also be used for the Keptn integration -> https://github.com/keptn-sandbox/k6-service/

**Comment by jainammm** [comment]
I support this feature request. It'll be good to have an official K6 extension docker image. Users would get more flexibility to run in production systems than always installing xk6 from golang and then building binary and using it in their pipelines. Thanks!

**Comment by Moon1706** [comment]
I'm going to continue to use this project, so I've builded images with versions [0.0.4](https://hub.docker.com/layers/moon1706/xk6-output-prometheus-remote/0.0.4/images/sha256-7943545ca6ffa8e009e840b9ba516c72ba5bdb241a23dc58bcf10694d90b4dfc?context=explore) and [0.0.5](https://hub.docker.com/layers/moon1706/xk6-output-prometheus-remote/0.0.5/images/sha256-902d68394c2d55296addb86da2292b51373411d425178cc60c150cb774fc32ff?context=explore) (now latest). I'm planning to support [my fork](https://github.com/Moon1706/xk6-output-prometheus-remote) of this project with custom build steps.

**Comment by Moon1706** [comment]
I will provide here build updates.

**Comment by Moon1706** [comment]
ANNONCE: Docker image [`0.0.6`](https://hub.docker.com/layers/moon1706/xk6-output-prometheus-remote/0.0.6/images/sha256-e59c28664e02ea5ff631597097f68f377aba034d2249c746404a2ebc7666dd46?context=explore) was created.

**Comment by Moon1706** [comment]
ANNONCE: Docker image [`0.0.7`](https://hub.docker.com/layers/moon1706/xk6-output-prometheus-remote/0.0.7/images/sha256-c7b397810897d359a0a1a43344ef1fe2a76747d428946295762cee67e4377c15?context=repo) was created.

**Comment by Moon1706** [comment]
ANNONCE: Docker image [0.0.8](https://hub.docker.com/layers/moon1706/xk6-output-prometheus-remote/0.0.8/images/sha256-22abe3230b57fe26bd2a2e2b14de1f1e0ef62ee9da4a9f76988dbbb1e564d24e?context=repo) was created.

**Comment by codebien** [comment]
We are releasing a new k6 version the next week that will include this extension so a docker image will finally be available. In the meantime, the `grafana/k6:master` image already includes it.

@Moon1706 I close this issue but feel free to continue to comment with the new versions if you make more builds. Thanks for the effort.
