### ISSUE TITLE
`K6_KEEP_URL_TAG` option not working in `v0.0.4`

### ISSUE THREAD

**Issue by BlakeSearlSonocent** [grafana/xk6-output-prometheus-remote#47]
Hi, thank you for this excellent extension.

We've recently tried upgrading to `v0.0.4` as there was a bug fix that we need in k6 `v0.40.0`.

We were using the `K6_KEEP_URL_TAG` option, set to `false` as we have a fair few `url`s that incorporate a uuid. This was working in `v0.0.3`.

Since the upgrade, we have found that the `url` tag is arriving in prometheus again, despite leaving `K6_KEEP_URL_TAG="false"` set. We've also tried `K6_KEEP_URL_TAG=false` as I noticed that the option is expecting a `Bool` but no luck there either.

Would you be able to offer any help? Thanks!

**Comment by BlakeSearlSonocent** [comment]
It looks like the support for it was dropped in this commit: https://github.com/grafana/xk6-output-prometheus-remote/commit/253b51ec74c17d20b6a6da82d5517e7f12a0c7e1

Here is the PR that added the option: https://github.com/grafana/xk6-output-prometheus-remote/pull/17

**Comment by codebien** [comment]
Hi @BlakeSearlSonocent,
it was removed mostly to make this extension more k6 native. Typically this is handled in `k6` using [URL-grouping](https://k6.io/docs/using-k6/http-requests/#url-grouping) or controlling the reported [system tags](https://k6.io/docs/using-k6/k6-options/reference#system-tags).

Does it not work for your use case? If not, can you expand, please?

**Comment by BlakeSearlSonocent** [comment]
Hey @codebien,

That makes a lot of sense, thank you for explaining and providing the resources. We're were using `URL-grouping` but not `system tags`. Dropping `url` from system tags works perfectly for us.

Thanks for your help 😃
