### ISSUE TITLE
Example dashboards are breaking due to postgres datasource

### ISSUE THREAD

**Issue by IamGroot19** [grafana/xk6-output-prometheus-remote#66]
The [sample dashboard](https://github.com/grafana/xk6-output-prometheus-remote/blob/main/grafana/dashboards/dashboard-results.json)  given in docs are breaking because some of the panels have postgres as datasource and psql queries for fetching data. The dockerfile is not spawning any postgres containers.

Can someone help me understand if I am missing something or this is a mistake in the file?

Thanks

**Comment by codebien** [comment]
Hi @IamGroot19,
thanks for reporting. I confirm that it is an error. @jwcastillo did some changes to the dashboard in #29. In the meanwhile, you could try to use the new version from the branch.

Feel free to open a PR if you know how to fix the issue otherwise I will fix it during the next weeks.

**Comment by IamGroot19** [comment]
Hi @codebien , thanks for confirming. Sorry, I dont have the bandwidth to help fix this issue. Can you elaorate bit more on 
> In the meanwhile, you could try to use the new version from the branch.

By branch,  did you mean the main branch?

**Comment by codebien** [comment]
@IamGroot19  No, I meant from the branch of #46 so `jwcastillo:new_version_dashboard`.

**Comment by javaducky** [comment]
@IamGroot19, we went ahead and merged #46 so refreshing your copy of the repository should now have a better Grafana dashboard.
