### ISSUE TITLE
Allow for custom labels when pushing to Prometheus, such as hostname

### ISSUE THREAD

**Issue by jdheyburn** [grafana/xk6-output-prometheus-remote#8]
We run k6 across multiple instances, it would be helpful to allow a hostname label (and others I'm sure) that would allow Prometheus to receive multiple datapoints of the same metric, and aggregate based on host.

**Comment by yorugac** [comment]
Hi @jdheyburn 
k6 has support for [custom tags](https://k6.io/docs/using-k6/tags-and-groups/#user-defined-tags) -- could you try adding those to your scripts? The extension should add them as a label then.

**Comment by jdheyburn** [comment]
Great, thanks for the info!
