### ISSUE TITLE
Custom tags

### ISSUE THREAD

**Issue by nareshgnT** [grafana/xk6-output-prometheus-remote#9]
Is it possible to add custom tags to default metrics? example, runId or app_name so that can filter by it if there are multiple different ran it the same time.

**Comment by yorugac** [comment]
Yes, it's part of k6 functionality; please see here: https://k6.io/docs/using-k6/tags-and-groups/#user-defined-tags

**Comment by yorugac** [comment]
Closing the issue as this functionality is supported via tag system in k6.

**Comment by nareshgnT** [comment]
thanks @yorugac, I am able to set the tag using cli cmd and able to see same in prometheus
