### ISSUE TITLE
checks cannot be filtered by url or name, the tag is not available

### ISSUE THREAD

**Issue by jwcastillo** [grafana/xk6-output-prometheus-remote#95]
Since K6 allows you to use different checks for each URL, is it possible to add the tag in the check metric? This would allow you to filter them by the URLs that use them. 
![image](https://user-images.githubusercontent.com/443948/210155518-ef3a3fd0-ac4a-44f5-99cb-97ac6e5f9f89.png)

**Comment by codebien** [comment]
This is a logic defined by the k6 core, the output is mostly proxying what it gets from the core. As you can read in https://github.com/grafana/k6/issues/1066, the idea is to simplify the Checks API, so I'm not sure we will implement this feature soon. As a workaround, you could set directly from the script the Check's name as the same as the Request's name. Does it sound reasonable to you?

**Comment by codebien** [comment]
I close for lack of details. @jwcastillo feel free to reopen if needed.
