### ISSUE TITLE
filter the vus by scenarios

### ISSUE THREAD

**Issue by jwcastillo** [grafana/xk6-output-prometheus-remote#96]
Each scenario can have a different number of vus, is it possible to add the scenario tag in the check metric?

**Comment by codebien** [comment]
Hi @jwcastillo,
I'm still trying to figure out if I got your question, let me try.

Do you mean the `vus` gauge metric? VUs metric is a global concept for k6 at the moment. To have it split by scenario, it requires a change on k6 https://github.com/grafana/k6/issues/1833. Can you report your use case directly in that issue, please?

**Comment by codebien** [comment]
I close it because it doesn't seem to be a direct issue for the output. Feel free to reopen if needed.
