### ISSUE TITLE
OAuth Authentication

### ISSUE THREAD

**Issue by peterghaddad** [grafana/xk6-output-prometheus-remote#97]
Currently Basic Authentication is supported. Does OAuth2 support exist? Not all Prometheus instances can enable Basic Auth, and using a OAuth2 is considered a better practice.

**Comment by peterghaddad** [comment]
Hi @codebien, the use case is that Basic Auth isn't considered the best practice when authenticating to Prometheus. Prometheus accepts Bearer tokens i.e the `Authentication` header which would be extremely helpful. Also, there are additional steps for setting up Prometheus to accept Basic Auth depending on how it was deployed.

**Comment by codebien** [comment]
Ok, then I close this issue because it seems a duplicate of https://github.com/grafana/xk6-output-prometheus-remote/issues/54. Please, add your :+1: there so we can consider the right priority during our planning.

Feel free to reopen and add more details if you think #54 wouldn't be enough.
